export { HomeComponent } from './home/home.component';
export { IpaComponent } from './ipa/ipa.component';
export { InputComponent } from './input/input.component';
export { LoginComponent } from './login/login.component';
export { OutputComponent } from './output/output.component';
export { PageNotFoundComponent } from './page-not-found/page-not-found.component';
export { ProfileComponent } from './profile/profile.component';
export { RegisterComponent } from './register/register.component';
export { WordGeneratorComponent } from './word-generator/word-generator.component';
