export enum Manner {
  Nasal = 'NASAL',
  Stop = 'STOP',
  Sibilant_Aff = 'SIBILANT_AFFRICATE',
  Non_sib_Aff = 'NON_SIB_AFF',
  Sibilant_Fri = 'SIBILANT_FRICATIVE',
  Non_sib_Fri = 'NON_SIB_FRI',
  Approximant = 'APPROXIMANT',
  Tap = 'TAP',
  Trill = 'TRILL',
  Lateral_Aff = 'LATERAL_AFF',
  Lateral_Fri = 'LATERAL_FRI',
  Lateral_App = 'LATERAL_APP',
  Lateral_T = 'LATERAL_T',
  Ejec_St = 'EJEC_ST',
  Ejec_Aff = 'EJEC_AFF',
  Ejec_Fri = 'EJEC_FRI',
  Ejec_Lat_Aff = 'EJEC_LAT_AFF',
  Ejec_Lat_Fri = 'EJEC_LAT_FRI',
  Clic_Tenuis = 'CLIC_TENUIS',
  Clic_Nas = 'CLIC_NAS',
  Clic_Lateral = 'CLIC_LATERAL',
  Clic_Lat_Nas = 'CLIC_LAT_NAS',
  Implosive = 'IMPLOSIVE'
}
